CHANGELOG.md
govuk_frontend/templates.py
tests/test_environment.py

`join_path` was trying to join paths even when the path wasn't relative
(i.e. didn't start with `./` or `../`). This commit fixes this and adds tests.

Fix bug with `join_path`

---

README.md

Spotted a small missed rename in an example. Also specify that we're talking about jinja**2** in prose of readme.

readme: catch missed module rename in example 

---

govuk_frontend_jinja/templates.py
tests/components/test_summary_list.py
tests/conftest.py
tests/test_helpers.py
tests/test_templates.py

@jonheslop found that the summary list component wasn't working; this PR adds a transformation to `njk_to_j2` to fix it; it also adds tests (although these will currently be skipped because we're testing against govuk-frontend 2.4.0.

Add support for summary list component

---

CHANGELOG.md
govuk_frontend_jinja/flask_ext.py
requirements-dev.txt
tests/test_flask_ext.py
tox.ini

In Flask < 1.1.x jinja_options is an ImmutableDict, so we need to copy
it before making modifications.

Fix flask_ext to work with Flask 1.0.x

---

setup.py
tox.ini

This allows users to install dependencies using pip directly if they wish:
$ pip install -e .[Flask,dev]

Move test/dev dependencies out of tox.ini and into setup.py

---

govuk_frontend_jinja/templates.py
tests/components/test_checkboxes.py
tests/components/test_radios.py

https://trello.com/c/x2jjzXJS
Two unrelated fixes here really.
Firstly a simple apostrophe fixup which nicely hides a dissimilarity between jinja & nunjucks.
Secondly an implementation of `__add__` for `NunjucksUndefined`.

xfail fixes: date-input & radios

---

govuk_frontend_jinja/templates.py
tests/components/test_file_upload.py
tests/components/test_textarea.py

https://trello.com/c/x2jjzXJS
Don't know if you want to apply this or leave it as an xfail, but this seems to me the way to fix it.
This includes our own copy of the upstream-fixed indent filter not yet included in a stable jinja2 release. Use this as `indent_njk` so we don't alter the behaviour of the whole application's jinja2 inadvertantly.

Fix overzealous re-escaping of Markup text by indent filter

---

govuk_frontend_jinja/templates.py
tests/components/test_character_count.py
tests/test_environment.py
tests/test_templates.py

Seems I forgot to create the PR for this one on friday. You're gonna love this one, but I think struggle to achieve its equivalent with a string replacement approach...
https://trello.com/c/x2jjzXJS
Note we don't wrap our `visit_CondExpr` method in their `@optimizeconst` decorator - it would just be another potentially fragile symbol to rely on from deep inside jinja and we can cope without its optimization in the rare case it doesn't just get forwarded on as a supercall anyway.

NunjucksCodeGenerator, a subclass that optionally behaves like nunjucks for inline conditionals

---

govuk_frontend_jinja/templates.py
tests/components/date_input/test_date_input.py
tests/test_templates.py

https://trello.com/c/x2jjzXJS
Custom implementations of the `Environment`'s `getitem` and `getattr` are used to detect these and attempt to take the best action when either of these are used. We limit this to just lookups with an `__njk` signature because we don't want to alter the behaviour of *all* of an app's jinja, and
unfortunately it's not possible to switch `Environment`s as jinja enters into an `.njk` file. So we need to specially tag those `.length` and `.items` accesses that originated from an njk file in the preprocess step.
This is the only way I could think of reliably fixing `test_date_input_with_default_items`. The issue with this test is how `components/date-input/template.njk` assigns the result of the `params.items` lookup to a variable and then iterates over that later. …

handle .length and .items quirks by tagging uses with an __njk signature which is specially handled

---

CHANGELOG.md
govuk_frontend_jinja/flask_ext.py
tests/conftest.py
tests/page_template/test_page_template.py
tests/test_flask_ext.py

Ticket: https://trello.com/c/isyW25Fl/63-enable-fix-autoescaping-for-nunjucks-macros-in-frontends
Also closes issue https://github.com/alphagov/govuk-frontend-jinja/issues/6
We want to make sure that input from users is made safe by being escaped; this PR enables autoescaping in the Flask extension by default, by overriding its default autoescape selector to also include `njk` files.
We also explicitly enable autoescaping for our tests, so we can feel sure that this change won't break everything.

Enable autoescaping for Nunjucks templates

---

.travis.yml
govuk_frontend_jinja/templates.py
pytest.ini
setup.py
tests/components/checkboxes/test_checkboxes.py
tests/components/date_input/test_date_input.py
tests/components/file_upload/test_file_upload.py
tests/components/phase_banner/test_phase_banner.py
tests/components/radios/test_radios.py
tests/components/test_components.py
tests/test_flask_ext.py
tox.ini

In #37 @risicle noticed after we had merged that a test was being overwritten by a test with the same name in the same file.
This PR fixes that issue; to make sure that similar things don't happen in future it also adds [pyflakes](https://pypi.org/project/pyflakes/) to the test suite, which should catch this sort of thing.

Add pyflakes to catch duplicate test names and other small code issues

---

CHANGELOG.md
setup.py
tests/components/character_count/test_character_count.py
tests/components/textarea/test_textarea.py

* Enable autoescaping for Nunjucks templates in Flask ([#37](https://github.com/alphagov/govuk-frontend-jinja/pull/37))
* We have 100% coverage for components in GOV.UK Design System v2.13.0! :raised_hands: ([#3](https://github.com/alphagov/govuk-frontend-jinja/issues/3))
* Fix tests for page template ([#32](https://github.com/alphagov/govuk-frontend-jinja/pull/32))
* Fix some instances where Jinja was unable to resolve `params.items` ([#24](https://github.com/alphagov/govuk-frontend-jinja/pull/24))

Release v0.5.0-alpha

---

govuk_frontend_jinja/flask_ext.py
govuk_frontend_jinja/templates.py
tests/test_flask_ext.py

This PR fixes issue #40.
The use of multiple inheritance wasn't working because `govuk_frontend_jinja.Environment.__init__`'s call signature didn't accept positional arguments; fixing this bug allowed the proper method resolution order to be specified, and now the init function that adds `indent_njk` gets called as expected.
The lesson here is probably "don't use multiple inheritance", but oh well 🤷‍♂

Fix bug in Flask extension where indent_njk was not available

---

govuk_frontend_jinja/templates.py
tests/test_environment.py

Fixes #49.
We need this so we can use govuk-frontend v3 with the user frontend, see https://trello.com/c/5FhjhxMd/139-3-migrate-user-frontend-to-govuk-frontend-v3

Add support for Nunjucks strict equality operator `===`

---

CHANGELOG.md
setup.py

* Fix links in README (thanks [@dalepotter](https://gitbhub.com/dalepotter)!) ([#34](https://github.com/alphagov/govuk-frontend-jinja/pull/34))
* You can now use the Nunjucks strict equality operator `===` in templates ([#50](https://github.com/alphagov/govuk-frontend-jinja/pull/50))

Release v0.5.2-alpha

---

CHANGELOG.md
govuk_frontend_jinja/templates.py
tests/components/summary_list/test_summary_list.py
tests/components/summary_list/test_summary_list_with_some_actions.t.html
tests/components/summary_list/test_summary_list_with_some_actions.x.html
tests/test_templates.py

govukSummaryList creates the `anyRowHasActions` variable outside a loop and changes it within a loop.
https://github.com/alphagov/govuk-frontend/blob/844a51e07c643cec84c6425a8cbda568261c78c5/src/govuk/components/summary-list/template.njk#L10-L14
Jinja doesn't support this as is, so this adds namespacing for it.

Add fix for summary list variable set within loop

---

.secrets.baseline
CHANGELOG.md
govuk_frontend_jinja/templates.py
setup.py
tests/test_templates.py

As of 3.5.0 of GOV.UK Frontend, the Character Count component includes an int concatenation in the hint: https://github.com/alphagov/govuk-frontend/blob/befc348ab6aec7c25c61c71ebf363a6b3bb36949/src/govuk/components/character-count/template.njk#L30
This is causing errors updating Briefs FE to v3, so this is a quick fix for it, before we switch over to the Land Registry govuk-frontend-jinja.

Add support for character count int concatenation

---

govuk_frontend_jinja/templates.py
tests/test_templates.py

govukCheckboxes includes a `for attribute, value in item.attributes` iteration which fails.
This can be fixed by using `.items()` instead of the Python default `.keys()`

Add items() to item.attributes

---

CHANGELOG.md
govuk_frontend_jinja/templates.py
tests/components/checkboxes/test_checkboxes.py
tests/components/checkboxes/test_checkboxes_with_a_conditional.t.html
tests/components/checkboxes/test_checkboxes_with_a_conditional.x.html
tests/components/radios/test_radios.py
tests/components/radios/test_radios_with_a_conditional.t.html
tests/components/radios/test_radios_with_a_conditional.x.html
tests/test_templates.py

In the Radios and Checkboxes component, isConditional is set in a `{% for %}` block, so needs to be namespaced.
```{% set isConditional = false %}
{% for item in params.items %}
{% if item.conditional %}
{% set isConditional = true %}
{% endif %}
{% endfor %}
```
This PR does that.

Add namespacing for isConditional

---

CHANGELOG.md
govuk_frontend_jinja/templates.py
tests/components/table/test_table.py
tests/components/table/test_table_with_cell_attributes.t.html
tests/components/table/test_table_with_cell_attributes.x.html
tests/test_templates.py

Similarly to other components with an iteration through `attributes`, we need to allow for table cells to properly iterate attributes using `.items()`.

Fix cell attributes iteration

---

CHANGELOG.md
govuk_frontend_jinja/templates.py
tests/components/summary_list/test_summary_list_with_actions.t.html
tests/components/summary_list/test_summary_list_with_actions.x.html
tests/test_templates.py

We currently add a check if and when we encounter a `for attribute, value in` iteration.
This PR simplifies this a bit.
I've left the `(foo|bar)` structure to make it explicit what we've added. However, even
in those cases we have not explicitly checked ALL uses of that change.
This may be _good enough_ until we deprecate this repo - alternatively, we will have to create explicit test cases for each example of this pattern in govuk-frontend: https://github.com/alphagov/govuk-frontend/search?l=HTML%2BDjango&q=for+attribute%2C+value+in
This PR adds one of those specific tests - for summary list actions.

Simplify attribute, value iterations

---

.github/workflows/test.yml
.travis.yml
README.md
tox.ini

https://trello.com/c/jfRAF4AR/1562-migrate-govuk-frontend-jinja-from-travis-to-github-actions
This app was missed when migrating from Travis CI from Github Actions.

replace travis CI with github actions

---

.github/workflows/test.yml
README.md
govuk_frontend_jinja/templates.py
setup.py
tests/test_environment.py
tests/test_templates.py
tox.ini

There were some compatibility issues with the latest GOV.UK Frontend.
These included:
- Strict inequality, i.e. `!==`
- `.values` calling the inbuilt dict method
I’ve made the updates so these features now work. I’ve not added tests for GOV.UK Frontend v4 as I found this to be too difficult. Plus our aim is to move away from this eventually and use real Jinja macros.

Make some updates for GOV.UK Frontend v4

---

CHANGELOG.md
setup.py

* Make compatible with GOV.UK Frontend v4 ([#69](https://github.com/Crown-Commercial-Service/govuk-frontend-jinja/pull/69))

Release 0.6.0-alpha
